### ISSUE TITLE
state value is not json in parse-auth

### ISSUE THREAD

**Issue by alexantom** [aws-samples/cloudfront-authorization-at-edge#38] opened 2020-03-05 18:26 UTC
I have setup whole stack using cloudformation and its works great.  

At one point  i got this as state value `eyJub25jZSI6Ii4xQUZkZVVONVQuZn5 VXciLCJyZXF1ZXN0ZWRVcmkiOiIvIn0=`

when i tried to  `console.log(Buffer.from(stateval, 'base64').toString())` i get this value  

`{"nonce":".1AFdeUN5T.f~U]��\]Y\�Y\�H���ȟ` which is not a json  and it errors at 

https://github.com/aws-samples/cloudfront-authorization-at-edge/blob/master/src/lambda-edge/parse-auth/index.ts#L20

What is the root cause for this issue?

**Comment by ottokruse** [comment] 2020-03-09 10:18
Mmm.... that makes no sense to me. Is this when the nonce mismatch occurs?

Are your using federation with you Cognito user pool? If so, have a read of this #32 and #21 they explain why we added base64 encoding of state.

Was this an incident? How often does this happen?

**Comment by alexantom** [comment] 2020-03-10 05:40
@ottokruse  this happened only twice or so, couldn't reproduce the issue   again. Let me take a look into the issue mentioned

**Comment by ottokruse** [comment] 2020-04-07 13:57
Believe this was caused by the + / and = characters that can be present in base64 encoded strings.

We URI encoded these to be able to put them in the URL state query param, that should be returned to us by Cognito **unaltered** after sign-in. However, together with another uses I was able to uncover that Cognito URL decodes the state query param on the way back. Our code did not expect that.

Implemented a work around in #47 that should prevent any unexpected URI component decoding.

Not 100% sure that this solves your issue, the state param you mention contains a space character, which I cannot explain - copy-paste typo?

Closing this issue for now. Please report back if this issue persists

**Closed by ottokruse** 2020-04-07 13:57 UTC

**Comment by alexantom** [comment] 2020-05-09 20:23
Thanks @ottokruse  for the details, will take a look
